# Need these for a more recent CMake on Linux
sudo: required
dist: trusty

os:
  - linux

language: cpp

compiler:
  - gcc
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - g++-6

install:
    - "[ $CXX = g++ ] && export CXX=g++-6 || true"

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .

after_script:
  - cmake --build . --target test

